name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        dockerfile: 
          - 9000/jre/Dockerfile
          - 9000/jdk/Dockerfile
          - 9000/alpine-jre/Dockerfile
          - 9000/alpine-jdk/Dockerfile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: verify diffs
      run: ./update.sh && git diff --quiet HEAD
    - name: Build all the things
      run: docker build -< ${{ matrix.dockerfile }}

